falconeye/characters/urls.py
from django.urls import path

from .views import PeopleListView, PeopleCreateView, PeopleCreateApiView

app_name = "characters"
urlpatterns = [
    path("", PeopleListView.as_view(), name="list"),
    path("create", PeopleCreateView.as_view(), name="create"),
    path("api/create", PeopleCreateApiView.as_view(), name="api-create"),
]

falconeye/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("falconeye.characters.urls")),
    path("users/", include("falconeye.users.urls")),
    path("admin/", admin.site.urls),
]

falconeye/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import LoginView


app_name = "users"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

falconeye/characters/models.py
from django.db import models

from .validators import birth_year_validator


class GenderChoices(models.TextChoices):
    MALE = "male", "Male"
    FEMALE = "female", "Female"
    NOT_APPLICABLE = "n/a", "Not Applicable"
    UNKNOWN = "unknown", "Unknown"


class Planet(models.Model):
    name = models.CharField(max_length=255)
    population = models.IntegerField()
    climate = models.CharField(max_length=255)
    terrain = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class People(models.Model):
    name = models.CharField(max_length=255)
    birth_year = models.CharField(
        max_length=255,
        validators=[birth_year_validator],
    )
    gender = models.CharField(max_length=10, choices=GenderChoices.choices)
    homeworld = models.ForeignKey(
        Planet,
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self) -> str:
        return self.name


class Vehicle(models.Model):
    name = models.CharField(max_length=255)
    model = models.CharField(max_length=255)
    manufacturer = models.CharField(max_length=255)
    pilots = models.ManyToManyField(People, related_name="vehicles")

    def __str__(self) -> str:
        return f"{self.model} - {self.name}"

falconeye/characters/views.py
from django.views.generic import ListView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics
from rest_framework import permissions

from .serializers import PeopleSerializer

from .models import People


class PeopleListView(LoginRequiredMixin, ListView):
    model = People


class PeopleCreateView(LoginRequiredMixin, TemplateView):
    template_name = "characters/people_form.html"


class PeopleCreateApiView(generics.CreateAPIView):
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = PeopleSerializer

falconeye/users/views.py
from django.contrib.auth.views import LoginView as DjangoLoginView


class LoginView(DjangoLoginView):
    template_name = "users/login.html"
    redirect_authenticated_user = True

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Star Wars |{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
    <style>
        .errors {
            width: 100%;
            margin-top: .25rem;
            font-size: 80%;
            color: #dc3545;
        }
    </style>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/characters/people_form.html
{% extends "base.html" %}
{% load static %}

{% block title %} Form {% endblock title %}

{% block content %}
{% include "partials/header.html" %}

<div class="row mt-5 justify-content-center">
    <div class="col-12">
        <div id="people-form"></div>
    </div>
</div>

<script src="{% static 'build/bundle.js' %}"></script>
{% endblock content %}

templates/characters/people_list.html
{% extends "base.html" %}

{% block title %} Characters {% endblock title %}

{% block content %}
{% include "partials/header.html" %}

<div class="row mt-5 justify-content-center">
    <div class="col-12">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Birth Year</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Home World</th>
                </tr>
            </thead>
            <tbody>
                {% for people in people_list %}
                <tr>
                    <th scope="row">{{ people.name }}</th>
                    <td>{{ people.birth_year }}</td>
                    <td>{{ people.gender }}</td>
                    <td>{{ people.homeworld }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/partials/header.html
<div class="row mt-5 justify-content-center">
    <div class="col-6 mt-5">
        <p><b>Welcome, {{ request.user.username|title }}</b></p>
    </div>
    <div class="col-6 mt-5 text-right">
        <a href={% url "characters:create" %} class="btn btn-outline-primary">Add People</a>
        <a href={% url "users:logout" %} class="btn btn-outline-danger">Logout</a>
    </div>
</div>

templates/users/login.html
{% extends "base.html" %}

{% block title %} Login{% endblock title %}

{% block content %}
    <div class="row mt-5 justify-content-center">
        <div class="col-4 mt-5">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">Email address</label>
                    <input type="text" class="form-control" id="id_username" placeholder="Username" name="username">
                    {% if form.errors %}
                        {% for field in form %}
                            {% if field.name == "username" %}
                                {% for error in field.errors %}
                                    <small class="text-danger">{{ error }}</small>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="id_password">Password</label>
                    <input type="password" class="form-control" id="id_password" placeholder="Password" name="password">
                    {% if form.errors %}
                        {% for field in form %}
                            {% if field.name == "password" %}
                                {% for error in field.errors %}
                                    <small class="text-danger">{{ error }}</small>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    <div class="row mt-3 justify-content-center">
        <div class="col-4">
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock content %}